name: Create Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Release
        run: |
          read -r VERSION<${{ github.workspace }}/necromancy.version
          echo $NEC_VERSION