name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Define variables
        run: sh ./{{ github.workspace }}/release.sh

      - name: Run a multi-line script
        run: |
          read -r VERSION<${{ github.workspace }}/necromancy.version
          echo $VERSION
          echo TEST
        
